### PR TITLE
Lyric options added

### PR DESCRIPTION
**Pull request by ayhankuru**
#3

### CODE REVIEW

**Comment by Jack12816** [comment]
Please follow the commit message style.

**Comment by ayhankuru** [comment]
@Jack12816 I'm sorry , I will consider the necessary warnings

**Comment by ayhankuru** [comment]
I myself developed for use ,thanks

**Comment by Jack12816** [comment]
This is actually not the open source spirit. Just customize the library for your needs and don't give the changes back. You wasted my time with this PR if you just close it - as it works for you. ._.

**Pull request closed without merging**
